# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38423e4b236a5a8e7c922a9a023be1ef985f45ccf1aec4a0f2db1d099e530920cdb5f5ffdcfcd2c49d5e42fc6ae6947ff7da5bb7f36bfc20caa65a56599070a3

test:
  secret_key_base: 6b5d66edfe3ce010199fe2e927ac38501ef36305feac973883e77ccfd858481177c080d2ca1a53c228b6f5248e47f8c4a008d55df99ea11e7d1e116d1a4e5060

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
